# Generated by Django 5.2.5 on 2025-10-01 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fcm_django', '0011_fcmdevice_fcm_django_registration_id_user_id_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestedFCMDevice',
            fields=[
                ('fcmdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.FCM_DJANGO_FCMDEVICE_MODEL)),
                ('attest_nonce', models.CharField(blank=True, max_length=255, null=True)),
                ('attest_nonce_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Attested FCM device',
                'verbose_name_plural': 'Attested FCM devices',
            },
            bases=('fcm_django.fcmdevice',),
        ),
    ]
